version: "3.7"

services:

  traefik:
    image: "traefik:2.0"
    command:
      - --providers.docker=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    networks:
      - service
    restart: on-failure

  db:
    image: "mongo:4.2"
    volumes:
      - mongo
    networks:
      - service
    restart: on-failure

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.front
    labels:
      - traefik.http.routers.frontend.rule=Host(`wheelly.xyz`)
      - traefik.http.services.frontend.loadbalancer.server.port=8080
    networks:
      - service
    restart: on-failure

  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    labels:
      - traefik.http.routers.backend-api-microcopy.rule=Host(`wheelly.xyz`) && PathPrefix(`/api`)
      - traefik.http.services.backend-api-microcopy.loadbalancer.server.port=8080
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - service
    restart: on-failure

networks:
  service:
