export const userConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOFF_REQUEST: 'LOGOFF_REQUEST',
    LOGOFF_SUCCESS: 'LOGOFF_SUCCESS',
    LOGOFF_FAILURE: 'LOGOFF_FAILURE',

    PWD_RESTORE_REQUEST: 'PWD_RESTORE_REQUEST',
    PWD_RESTORE_SUCCESS: 'PWD_RESTORE_SUCCESS',
    PWD_RESTORE_FAILURE: 'PWD_RESTORE_FAILURE',

    RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
    SET_OK_MESSAGE: 'SET_OK_MESSAGE',
    RESET_OK_MESSAGE: 'RESET_OK_MESSAGE'

};
