export const userConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOFF: 'LOGOFF',

    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',

    RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
    SET_OK_MESSAGE: 'SET_OK_MESSAGE',
    RESET_OK_MESSAGE: 'RESET_OK_MESSAGE',

    PLAY_BUTTON_CLICKED: 'PLAY_BUTTON_CLICKED',
    DEFAULT_VIDEO: "Q5BQTj4pzZo",

    STATS_WRITE_FAILURE: 'STATS_WRITE_FAILURE',
};
