openapi: 3.0.1
info:
  title: kimaya-test-task
  description: Coolest app for searching YouTube
  version: 1.0.0
servers:
  - url: /api/v1

paths:
  /user/signup:
    post:
      tags:
        - Sign up new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Return new user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


  /user/login:
    post:
      tags:
        - Loggin in user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        200:
          description: Return user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /main/stats:
    post:
      tags:
        - Write user stats
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                videoId:
                  type: string
                searchString:
                  type: string
                videoDuration:
                  type: number

      responses:
        200:
          description: Return ok

  /admin:
    get:
      tags:
        - Show stats for admin user only
      responses:
        200:
          content:
            application/json:

  /main/search:
    get:
      tags:
        - Search YouTube
      parameters:
        - name: q
          in: query
          description: Search string for YouTube
          required: true
          schema:
            type: string
            minimum: 3
            maximum: 100
      responses:
        200:
          description: Return YouTube json
          content:
            application/json:
              schema:
                type: object


components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
